allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def newBuildDir = rootProject.layout.buildDirectory.dir("../../build").get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    def newSubprojectBuildDir = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}

gradle.projectsEvaluated {
    subprojects {
        plugins.withId("com.android.library") {
            def libExt = extensions.findByName("android")
            if (libExt != null && libExt.compileSdk < 36) {
                libExt.compileSdk = 36
                println("Forced ${project.name} compileSdk to 36")
            }
        }
    }
}
